### ISSUE TITLE
Node restart fails sometimes

### ISSUE THREAD

**Issue by mcartmel** [justparking/feature_nodeluiunify#41]
Error appears in the console:
```
07-08 12:37:57.55 java.lang.NullPointerException
07-08 12:37:57.56 (Python and Node script(s) loaded with errors (took 14ms); calling 'main' if present...)
07-08 12:37:57.56 'main' completed with errors - java.lang.ClassCastException: org.python.core.PyNone cannot be cast to org.python.core.PyFunction
```

**Comment by mcartmel** [comment]
Further detail in the host logs:
```
07-08 13:19:59.02 The bindings could not be applied to the Python instance.
java.lang.NullPointerException
	at org.nodel.core.NodelClients.release(NodelClients.java:355)
	at org.nodel.core.NodelClientEvent.close(NodelClientEvent.java:429)
	at org.nodel.host.BaseNode.cleanupBindings(BaseNode.java:782)
	at org.nodel.jyhost.PyNode.applyConfig0(PyNode.java:619)
	at org.nodel.jyhost.PyNode.access$900(PyNode.java:84)
	at org.nodel.jyhost.PyNode$8.call(PyNode.java:527)
	at org.nodel.jyhost.PyNode$8.call(PyNode.java:523)
	at org.nodel.Threads$2.run(Threads.java:291)
	at java.lang.Thread.run(Unknown Source)
07-08 13:19:59.02 (Python and Node script(s) loaded with errors (took 6ms); calling 'main' if present...)
07-08 13:19:59.02 'main' completed with errors - java.lang.ClassCastException: org.python.core.PyNone cannot be cast to org.python.core.PyFunction
```

**Comment by justparking** [comment]
Moved to https://github.com/museumsvictoria/nodel/issues/152
